import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// import Dummy from "../components/dummy";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* <Dummy/> */}
      <style jsx>
        {`
          .myspan {
            // color: red;
            font-size: 3rem;
            font-weight: bold;
          },

          
         
          }
        `}
      </style>
      <Head>
        <title>&lt;Hunnting Coder/&gt;</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <span className="myspan dummy">&lt;Hunnting Coder/&gt;</span>
          <p>Learn to code by watching others</p>
          <div className={styles.imagewrap}>
            {" "}
            <img
              alt="img"
              className={styles.myImg}
              src="/home.jpg"
              width={237}
              height={158} 
            ></img>
          </div>
        </div>
        <div className="blogs">
          <h2 style={{ fontSize: "38px" }}>Popular Blogs</h2>

          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>js is goood language</p>
          </div>

          <div className="blogItem">
            <h3>How to learn javascript</h3>
            <p>js is goood language</p>
          </div>
        </div>
      </main>
    </>
  );
}
